# Generated by Django 3.2.8 on 2021-11-15 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211115_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feu', models.CharField(max_length=150)),
                ('ne', models.DateField(null=True)),
                ('decede', models.DateField(null=True)),
                ('dateCeremony', models.DateField(null=True)),
                ('item', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
                ('morgue', models.CharField(blank=True, default='', max_length=50)),
                ('total_amt', models.FloatField()),
                ('total_rest', models.FloatField()),
                ('paid_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '4. Les Commandes',
            },
        ),
        migrations.RemoveField(
            model_name='cartorderitems',
            name='order',
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': '1. Customers'},
        ),
        migrations.DeleteModel(
            name='CartOrder',
        ),
        migrations.DeleteModel(
            name='CartOrderItems',
        ),
        migrations.AddField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.products'),
        ),
    ]
