# Generated by Django 3.2.8 on 2021-11-15 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20211115_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='total',
            new_name='avance',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='total_amt',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='total_rest',
        ),
    ]
