# Generated by Django 3.2.8 on 2021-11-15 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211115_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='item',
            new_name='name',
        ),
    ]
